<!DOCTYPE html>
<html lang="en" class="bg-slate-900 text-slate-100">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?= $headTags ?? ''; ?>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://unpkg.com/lucide@latest"></script>
</head>
<body class="min-h-screen flex flex-col font-sans">
    <!-- Header -->
    <header class="bg-slate-950 border-b border-rose-600/30 sticky top-0 z-50">
        <div class="max-w-7xl mx-auto px-4 py-4 flex items-center justify-between">
            <div class="flex items-center space-x-3">
                <span class="px-2.5 py-1 bg-rose-600 text-white font-black text-xs uppercase tracking-widest rounded">Magazine Pro</span>
                <a href="/" class="text-2xl font-black text-white tracking-tight uppercase">BLOG<span class="text-rose-500">BUSTER</span></a>
            </div>
            <nav class="hidden md:flex space-x-6 text-sm font-semibold text-slate-300">
                <a href="/" class="hover:text-rose-400">Home</a>
                <a href="/category/news" class="hover:text-rose-400">News</a>
                <a href="/category/tech" class="hover:text-rose-400">Tech</a>
                <a href="/admin/login" class="text-rose-400">Admin Portal</a>
            </nav>
        </div>
    </header>

    <!-- Main Editorial Content -->
    <main class="flex-1 max-w-7xl w-full mx-auto px-4 py-8 grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div class="lg:col-span-2 space-y-6">
            <h2 class="text-xl font-bold uppercase tracking-wider text-rose-500 border-b border-rose-500/20 pb-2">Top Headlines</h2>
            <?php if (!empty($posts)): ?>
                <?php foreach ($posts as $post): ?>
                    <article class="p-6 bg-slate-800/80 border border-slate-700/60 rounded-2xl space-y-3">
                        <span class="text-xs font-bold text-rose-400 uppercase tracking-widest"><?= htmlspecialchars($post['category_name'] ?? 'General'); ?></span>
                        <h3 class="text-xl font-bold text-white hover:text-rose-400">
                            <a href="/<?= htmlspecialchars($post['slug']); ?>"><?= htmlspecialchars($post['title']); ?></a>
                        </h3>
                        <p class="text-slate-300 text-sm line-clamp-2"><?= htmlspecialchars(strip_tags($post['content'])); ?></p>
                    </article>
                <?php endforeach; ?>
            <?php else: ?>
                <p class="text-slate-400 text-sm">No articles published yet.</p>
            <?php endif; ?>
        </div>

        <!-- Sidebar -->
        <aside class="space-y-6">
            <div class="p-6 bg-slate-800/80 border border-slate-700/60 rounded-2xl">
                <h3 class="text-sm font-bold text-white uppercase tracking-wider mb-3">Trending Stories</h3>
                <p class="text-xs text-slate-400">Real-time magazine updates generated by BLOGBUSTER Magazine Pro theme engine.</p>
            </div>
        </aside>
    </main>

    <!-- Footer -->
    <footer class="bg-slate-950 border-t border-slate-800 py-6 text-center text-xs text-slate-500">
        <p>&copy; <?= date('Y'); ?> BLOGBUSTER Magazine Pro Theme. All rights reserved.</p>
    </footer>
</body>
</html>
